# Generated by Django 3.1.1 on 2020-09-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200928_0225'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='enrollment',
            managers=[
            ],
        ),
    ]
