# Generated by Django 3.1.1 on 2020-10-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=models.TextField(verbose_name='Mensagens'),
        ),
    ]
